name: CI

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: "Lint the contracts"
        run: "make lint"

      - name: "Show the Foundry config"
        run: "forge config"

      - name: Build the contracts
        run: |
          forge --version
          forge build
        id: build

      - name: Run the tests
        run: |
          forge test -vvv
        id: test
  
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: foundry
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Slither
        uses: crytic/slither-action@main
        continue-on-error: true
        with:
          node-version: 16
          fail-on: medium

  gas-report:
    name: Gas Report
    runs-on: ubuntu-latest
    needs: foundry
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Generate Gas Report
        run: |
          forge test --gas-report | tee gasreport.ansi
        id: gen_gas_report

      - name: Compare Reports
        uses: Rubilmax/foundry-gas-diff@v3.11
        with:
          sortCriteria: avg,max
          sortOrders: desc,asc
          ignore: test/**/*
        id: gas_diff

      - name: Add Summary Comment
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # delete the comment in case changes no longer impact gas costs
          delete: ${{ !steps.gas_diff.outputs.markdown }}
          message: ${{ steps.gas_diff.outputs.markdown }}