name: Deploy Wiki

on:
  push:
    paths:
      # Trigger only when docs directory changes
      - "docs/**"
    branches:
      # And only on master branch
      - "master"

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Push Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        WIKI_DIR: docs/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ github.event.pusher.email }}
        GH_NAME: ${{ github.event.pusher.name }}